    //Get PostalCode Data
export const GET_POSTALCODE_INFO= 'GET_POSTALCODE_INFO';
export const GET_POSTALCODE_INFO_SUCCESS='GET_POSTALCODE_INFO_SUCCESS';
export const GET_POSTALCODE_INFO_ERROR='GET_POSTALCODE_INFO_ERROR';